{
 "title": "My Cloud App New",
 "description": "Primer monitoring dashboard",
 "tags": [
  "cloud",
  "my-app"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "log_search", "label": "Log Query" },
   { "name": "DS_PROMETHEUS", "label": "PROMETHEUS", "query": "${DS_PROMETHEUS}" },
   { "name": "DS_LOKI", "query": "${DS_LOKI}" }
  ]
 },
 "panels": [
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Memory (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_disk_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    { "expr": "process_memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "process_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Usage (B/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(network_out_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"my-app\"} |= `${log_search}` | json"
    }
   ]
  }
 ]
}