version: '3'
networks:
  net:
    driver: bridge
services:
  server:
    image: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-my-app}
      - OTEL_ENDPOINT=${OTEL_ENDPOINT:-http://otel-collector:4317/}
      - OTEL_TRACE_GRANULARITY=${OTEL_TRACE_GRANULARITY:-all}
    ports:
      - 8085:8080
    networks:
      - net
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "55681:55681" # zPages
      - "9091:9090" # Prometheus metrics
    networks:
      - net
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - net
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - net
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - net
  loki:
    image: grafana/loki:latest
    volumes:
      - loki-data:/loki
    ports:
      - "3100:3100"
    networks:
      - net
volumes:
  grafana_data:
    driver: local
  loki-data:
    driver: local
